server:
  port: 8080
spring:
  application:
    name: "Companies2"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:admin@clustercursojava.dasxz.mongodb.net/companies"